In [2]:
import seaborn as sns
data = sns.load_dataset('car_crashes')
data.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [9]:
data.iloc[:,0:7].cov()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
total,16.990902,5.086338,6.076992,15.381048,14.837975,-146.768484,-3.686589
speeding,5.086338,4.071303,2.336617,5.349704,4.344815,-27.943987,-3.303815
alcohol,6.076992,2.336617,2.989901,5.713491,5.100416,-52.599326,-4.833276
not_distracted,15.381048,5.349704,5.713491,20.330874,12.685394,-140.572871,-8.507441
no_previous,14.837975,4.344815,5.100416,12.685394,14.172755,-105.312296,-0.594528
ins_premium,-146.768484,-27.943987,-52.599326,-140.572871,-105.312296,31789.565170,2759.254746
ins_losses,-3.686589,-3.303815,-4.833276,-8.507441,-0.594528,2759.254746,616.823046

In [10]:
data.iloc[:,0:7].corr()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
total,1.000000,0.611548,0.852613,0.827560,0.956179,-0.199702,-0.036011
speeding,0.611548,1.000000,0.669719,0.588010,0.571976,-0.077675,-0.065928
alcohol,0.852613,0.669719,1.000000,0.732816,0.783520,-0.170612,-0.112547
not_distracted,0.827560,0.588010,0.732816,1.000000,0.747307,-0.174856,-0.075970
no_previous,0.956179,0.571976,0.783520,0.747307,1.000000,-0.156895,-0.006359
ins_premium,-0.199702,-0.077675,-0.170612,-0.174856,-0.156895,1.000000,0.623116
ins_losses,-0.036011,-0.065928,-0.112547,-0.075970,-0.006359,0.623116,1.000000

In [12]:
data.iloc[:,:7].corr(method='spearman')

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
total,1.000000,0.559365,0.894576,0.877605,0.958206,-0.118070,-0.000045
speeding,0.559365,1.000000,0.642654,0.562876,0.541699,-0.052128,-0.065341
alcohol,0.894576,0.642654,1.000000,0.796959,0.856012,-0.122899,0.020679
not_distracted,0.877605,0.562876,0.796959,1.000000,0.798136,-0.112853,0.015340
no_previous,0.958206,0.541699,0.856012,0.798136,1.000000,-0.036969,0.003937
ins_premium,-0.118070,-0.052128,-0.122899,-0.112853,-0.036969,1.000000,0.646697
ins_losses,-0.000045,-0.065341,0.020679,0.015340,0.003937,0.646697,1.000000